ergmm.statseval.latent1cluster.r:   Z.pm <- apply(Z.proc,c(1,2),mean)
ergmm.statseval.latent1cluster.r:##   Z.pmode <- array(0, dim=dim(z$Z)[1:2])
ergmm.statseval.latent1cluster.r:#    Z.pmode <- array(0, dim=c(dim(z$Z)[1],2))
ergmm.statseval.latent1cluster.r:    Z.pmode <- array(0, dim=c(Nnodes,ndim))
ergmm.statseval.latent1cluster.r:#    Z.pmode[k,] <- pmode(t(Z.proc[k,,]))
ergmm.statseval.latent1cluster.r:     Z.pmode[k,] <- pmode(aaa)
ergmm.statseval.latent1cluster.r:    Z.pmode <- Z.pm
ergmm.statseval.latent1cluster.r:     abvZ <- c(apply(l$Beta[,-(dp+1)],2,mean),Z.pmode)
ergmm.statseval.latent1cluster.r:     abvZ <- c(mean(l$Beta[,-(dp+1)]),Z.pmode)
ergmm.statseval.latent1cluster.r:   Z.pm <- NULL
ergmm.statseval.latent1cluster.r:   Z.pmode <- NULL
ergmm.statseval.latent1cluster.r:  l$Z.pmean <- Z.pm
ergmm.statseval.latent1cluster.r:  l$Z.pmode <- Z.pmode
ergmm.statseval.latentcluster.r:   Z.pm <- apply(Z.proc,c(1,2),mean)
ergmm.statseval.latentcluster.r:##   Z.pmode <- array(0, dim=dim(z$Z)[1:2])
ergmm.statseval.latentcluster.r:#    Z.pmode <- array(0, dim=c(dim(z$Z)[1],2))
ergmm.statseval.latentcluster.r:    Z.pmode <- array(0, dim=c(Nnodes,ndim))
ergmm.statseval.latentcluster.r:     Z.pmode[k,] <- pmode(t(Z.proc[k,,]))
ergmm.statseval.latentcluster.r:    Z.pmode <- Z.pm
ergmm.statseval.latentcluster.r:     abvZ <- c(apply(l$Beta[,-(dp+1)],2,mean),Z.pmode)
ergmm.statseval.latentcluster.r:     abvZ <- c(mean(l$Beta[,-(dp+1)]),Z.pmode)
ergmm.statseval.latentcluster.r:   Z.pm <- NULL
ergmm.statseval.latentcluster.r:   Z.pmode <- NULL
ergmm.statseval.latentcluster.r:  l$Z.pm <- Z.pm
ergmm.statseval.latentcluster.r:  l$Z.pmode <- Z.pmode
ergmm.statseval.latent.r:   Z.pm <- apply(z$Z,c(1,2),mean)
ergmm.statseval.latent.r:##  Z.pmode <- array(0, dim=dim(z$Z)[1:2])
ergmm.statseval.latent.r:#   Z.pmode <- array(0, dim=c(Nnodes, ndim))
ergmm.statseval.latent.r:    Z.pmode <- array(0, dim=c(Nnodes,ndim))
ergmm.statseval.latent.r:     Z.pmode[k,] <- pmode(aaa)
ergmm.statseval.latent.r:    Z.pmode <- Z.pm
ergmm.statseval.latent.r:   abvZ <- c(apply(l$Beta,2,mean),Z.pmode)
ergmm.statseval.latent.r:   Z.pm <- NULL
ergmm.statseval.latent.r:   Z.pmode <- NULL
ergmm.statseval.latent.r:  l$Z.pm <- Z.pm
ergmm.statseval.latent.r:  l$Z.pmode <- Z.pmode
